apiVersion: v1
kind: Service
metadata:
  name: hero
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 3000
  selector:
    app: hero
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hero
spec:
  selector:
    matchLabels:
      app: hero
  template:
    metadata:
      labels:
        app: hero
    spec:
      containers:
      - image: laserany/hero
        name: hero
        env:
          # Use secret in real usage
        - name: database
          valueFrom:
            configMapKeyRef:
              name: database
              key: name
        - name: user
          valueFrom:
            secretKeyRef:
              name: database
              key: user
        - name: password
          valueFrom:
            secretKeyRef:
              name: database
              key: password
        ports:
        - containerPort: 3000
          name: hero
